name: Deploy vue app to S3

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up node/npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up vue cli
        run: npm install
      - name: Build dist folder
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy dist contents to S3
        run: |
          aws s3 cp dist s3://screenstash \
          --recursive
