name: Destroy dynamic environment

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Change to TF directory
        run: cd terraform
      - name: Terraform destroy
        run: terraform destroy -lock=false --auto-approve
