name: Destroy dynamic environment

on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger destroy DE event
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/lloydamt/suggestions-terraform/dispatches \
          -d '{"event_type":"destroy-de"}'
