name: Deploy to dynamic environment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_to_DE:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Set up node/npm
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      # - run: npm i
      # - run: npm run build
      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # - name: Run Terraform
      #   run: |
      #     cd terraform
      #     terraform init
      #     terraform validate
      #     terraform apply -lock=false -var="bucket_name=${{ github.run_id }}" -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" --auto-approve
      - name: Fire event
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/lloydamt/suggestions-terraform/dispatches \
          -d '{"event_type":"dispatch-event"}'
