name: Deploy to dynamic environment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_to_DE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan
          | -var="bucket_name=${{ github.run_id }}" 
          | -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" 
          | -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          | --auto-approve
