name: Deploy to dynamic environment

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_to_DE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up node/npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm i
      - run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Set branch name as env variable
        run: |
          ls
          echo "branch_name=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Fire event
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/lloydamt/suggestions-terraform/dispatches \
          -d '{"event_type":"deploy-de", "client_payload": {"branch_name": "${{ env.branch_name }}", "run_id": "${{ github.run_id }}"}}'
